config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user_sessions" }

  root to: 'pages#newhome'
  get '/home',  to: 'pages#home',  as: 'home'
  get '/order', to: 'pages#order', as: 'order'
  get '/category', to: 'pages#category', as: 'category'
  get '/my_list', to: 'pages#my_list', as: 'my_list'
  authenticate :user do
    resources :users, only: [:show, :update, :edit]

    resources :recipes, only: [:new, :create, :edit]
    resources :baskets, only: [:create, :show]

    resources :detail_baskets, only: [:create, :index, :destroy]
  end

  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredient_recipes
  accepts_nested_attributes_for :ingredient_recipes

  has_many :ingredients, through: :ingredient_recipes
  accepts_nested_attributes_for :ingredients

  has_one_attached :photo
  validates :name, :description, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_recipe,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show update]

  before_action :set_recipe, only: %i[show update edit]
  before_action :set_user, only: %i[index show]

  def show
    # authorize @recipe
  end

  def index
    if params[:query].present?
      @recipes = Recipe.search_by_recipe(params[:query])
    else
      @recipes = Recipe.all
    end
    # authorize @recipes
  end

  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
    @recipe.ingredient_recipes.build
    # authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe successfully created"
      redirect_to recipe_path(@recipe)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    # authorize @recipe
  end

  def update
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
    # authorize @recipe
  end

  private

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :person_number, :query, :photo,
                                   ingredient_recipe_ids: [],
                                   ingredient_recipes_attributes: %i[id recipe_id ingredient_id ingredient_quantity])
  end
end

app/views/recipes/edit.html.erb
<h3>Edit Recipe</h3>
<%= render 'shared/recipe-new-edit-form' %>

app/views/recipes/index.html.erb
<div class="container">
  <h1 class="title-recipe-index">-All recipes-</h1>

  <%= form_tag recipes_path, method: :get do %>
   <div class="d-flex search">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control", id:"form-control-search",
      placeholder: "Find a recipe"%>
      <%= button_tag(type:"submit", class: "btn btn-flat") do %>
        <i class="fas fa-search text-decoration-none text-white h4"></i>
      <% end %>
   </div>
  <% end %>

  <% if @user %>
    <% if @user.moderator %>
      <%= link_to 'Add a recipe', new_recipe_path %>
    <% end %>
  <% end %>

  <div class="container">
    <% @recipes.each do |recipe| %>
      <div class="row">
        <div class="col-12">
          <%= link_to recipe_path(recipe), class:'text-decoration-none' do %>
            <div class="card-recipe">
              <div class="recipe-info">

                <h4 id="police-size"> <%= recipe.name %> </h4>
                <div class="small-line-under line-under-recipe-index">
                  
                </div>

              </div>
              <%= cl_image_tag recipe.photo.key, height: 300, width: 400, crop: :fill,  class: "recipe-image"%>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>
<br>
<br>

app/views/recipes/new.html.erb
<h3>Create a Recipe</h3>
<%= render 'shared/recipe-new-edit-form' %>

app/views/recipes/show.html.erb
<% content_for :meta_title, "#{@recipe.name} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @recipe.description %>
<%# content_for :meta_image, cl_image_path(@recipe.photo.key) %>
<div class="container">
  <div>
    <%#= cl_image_tag @recipe.photo.key, height: 300, width: 400, crop: :fill,  class: "image-show"%>

    <div class="stage coeur-show">
      <div class="heart"></div>
    </div>

    <%# a mettre plus gros, en rose, position absolute %>
  </div>
  <h1 class="title-show"> <span>-</span> <%= @recipe.name %> <span>-</span> </h1>
  <% if @user %>
    <% if @user.moderator %>
      <%= link_to edit_recipe_path(id:@recipe.id) do %>
        <i class="far fa-edit"></i>
        Edit this Recipe
      <% end %>
    <% end %>
  <% end %>
  <div class="card-show card-recette">
    <div class="show-margin">
      <div class="enter-number-person">
        <p><strong></strong></p>
        <%= simple_form_for @recipe, html: { id: "simple-form-person-number"} do |f| %>
          <%= f.input :person_number, label: false, collection: 1..8, include_blank: false, include_hidden: false, input_html: { class: "enter-number-person-box" }  %>
          <%= f.button :submit, value: "Adjust" , class:"btn-form btn-person"%>
        <% end %>

      <%= link_to detail_baskets_path(recipe: @recipe.id, person: @recipe.person_number), method: :post, class:"text-decoration-none" do %>
        <div class="btn-cart btn-recette">
          <p class="color-white"><i class="fas fa-cart-arrow-down"></i></p>
        </div>
      <% end %>
      </div>

      <div class="recette">
        <strong><p id="titre">Ingredients : </p></strong>
        <% @recipe.ingredient_recipes.each do |ingredient_recipe| %>
          <li>
            <span class='ingredient-recipe-quantity'> <%= (ingredient_recipe.ingredient_quantity * @recipe.person_number).round(2) %> </span>
            <%= ingredient_recipe.ingredient.unit %>
            <%= ingredient_recipe.ingredient.name %>
          </li>
        <% end %>
        <br>
        <div class="d-flex justify-content-center">
          <div class="small-line-under line-recipe-show"></div>
        </div>
        <br>

        <strong><p id="titre">Recipe :</p></strong>
        <div class="etape">
          <ol>
          <% @recipe.description.split(".").each do |step| %>
            <div class="container">
              <li class="text-justify"><%= step %></li>
              <br>
              <div class="d-flex justify-content-center">
                <div class="small-line-under line-recipe-show"></div>
              </div>
              <br>
            </div>
          <% end %>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <%= link_to detail_baskets_path(recipe: @recipe.id, person: @recipe.person_number), method: :post, class:"text-decoration-none" do %>
    <div class="btn-show">
      <p class="color-white">Add to my basket</p>
    </div>
  <% end %>
</div>