config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user_sessions" }

  root to: 'pages#newhome'
  get '/home',  to: 'pages#home',  as: 'home'
  get '/order', to: 'pages#order', as: 'order'
  get '/category', to: 'pages#category', as: 'category'
  get '/my_list', to: 'pages#my_list', as: 'my_list'
  authenticate :user do
    resources :users, only: [:show, :update, :edit]

    resources :recipes, only: [:new, :create, :edit]
    resources :baskets, only: [:create, :show]

    resources :detail_baskets, only: [:create, :index, :destroy]
  end

  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_logobar.html.erb
<div id="logobar">
  <div class="logobar-logo-items">
    <%= link_to '<i class="fas fa-clipboard-list text-decoration-none text-white"></i>'.html_safe, root_path %>
    <%= link_to 'MyList', root_path, class:"text-decoration-none text-white" %>
  </div>

  <%# <%= image_tag("icons/MyList_logo.jpg") %> 
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <%= link_to '<i class="fas fa-home text-decoration-none text-white h4"></i>'.html_safe, home_path, class:'padding' %>
    <%= link_to '<i class="fas fa-utensils text-decoration-none text-white h4"></i>'.html_safe, recipes_path,  class:'padding' %>
    <%= link_to '<i class="fas fa-shopping-basket text-decoration-none text-white h4"></i>'.html_safe, detail_baskets_path,  class:'padding' %>
  <div>
    <% if user_signed_in? %>
      <div class="nav-item dropup">
        <%# if current_user.photo.attached? %>
          <%# cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%# else %>
          <%# image_tag "https://images.affiches-et-posters.com//albums/3/47831/affiche-film-avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%# end %>
        <i class="fas fa-user text-decoration-none text-white h4" id= "navbarDropdown" data-toggle= "dropdown" ></i> 

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
        <%= link_to '<i class="far fa-user text-decoration-none text-white h4"></i>'.html_safe, new_user_session_path %>
    <% end %>
  </div>
</div>

app/views/shared/_recipe-new-edit-form.erb
<span id="all-ingredientsftw" data-ingredient="<%= @ingredients.to_json %>"></span>
<div class="container">
  <div class="intermediaire">
    <div class="recipe-new-edit-form">
      <%= simple_form_for @recipe do |f| %>
        <%= f.input :name, label: "Name of Recipe", input_html: { class: "w-100" } %>
        <%= f.input :description, label: "Steps to make Recipe", input_html: {rows: 10, class: "w-100" } %>
        <div class="form-flex">
          <p> Number of People: </p>
          <%= f.input :person_number, collection: 1..8, input_html: { class: "person-number-box" }, label: false, include_blank: false, include_hidden: false %>
        </div>
        <%= f.input :photo, as: :file, input_html: {multiple: false} %>
        <%= f.simple_fields_for :ingredient_recipes do |g| %>
          <div id="fieldsetContainer" class="simple-field-form-for-ingredient">
            <fieldset id="ingredient-0">
              <div class="form-flex">
                <p> Ingredient: </p>
                <%= g.association :ingredient, input_html: { class: "ingredient-box", id: 'ingredient-name-0' }, label: false, include_blank: false, include_hidden: false  %>
              </div>
              <%= g.label 'Quantity:  ' %>
              <%= g.number_field :ingredient_quantity, in: 1.0..10000.0, class: "quantity-box" %>
            </fieldset>
          </div>
        <% end %>
        <div class="submit-btn">
          <%= f.button :submit, class:"btn-form mr-0" %>
        </div>
      <% end %>
    </div>
    <button id="btnAddIngredient">Add another Ingredient</button>
  </div>
</div>