config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user_sessions" }

  root to: 'pages#newhome'
  get '/home',  to: 'pages#home',  as: 'home'
  get '/order', to: 'pages#order', as: 'order'
  get '/category', to: 'pages#category', as: 'category'
  get '/my_list', to: 'pages#my_list', as: 'my_list'
  authenticate :user do
    resources :users, only: [:show, :update, :edit]

    resources :recipes, only: [:new, :create, :edit]
    resources :baskets, only: [:create, :show]

    resources :detail_baskets, only: [:create, :index, :destroy]
  end

  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]
end

app/models/detail_basket.rb
class DetailBasket < ApplicationRecord
  belongs_to :ingredient_recipe, optional: true
  belongs_to :ingredient, optional: true
  belongs_to :basket, optional: true


  # def link_ingredient
  #   ingredient_id.nil? ? ingredient_recipe.ingredient : ingredient
  # end

  def quantity
    ingredient_quantity
    #ingredient_id.nil? ? ingredient_recipe.ingredient_quantity : ingredient_quantity
  end

  def name
    ingredient_id.nil? ? ingredient_recipe.ingredient.name : ingredient.name
  end

  def unit
    ingredient_id.nil? ? ingredient_recipe.ingredient.unit : ingredient.unit
  end

  def unit_price
    ingredient_id.nil? ? ingredient_recipe.ingredient.unit_price : ingredient.unit_price
  end

  def category
    ingredient_id.nil? ? ingredient_recipe.ingredient.category : ingredient.category
  end

  def ingredient_item
    ingredient_id.nil? ? ingredient_recipe.ingredient : ingredient
  end
end

app/controllers/detail_baskets_controller.rb
class DetailBasketsController < ApplicationController
  before_action :set_detail_basket, only: [:destroy, :edit, :update]

  def index
    @detail_baskets = DetailBasket.where(basket_id: current_user.baskets)
    @basket = Basket.find(current_user.baskets.first.id)
    @products = @detail_baskets.where.not(ingredient_id: nil)
    @recipes = @detail_baskets.where(ingredient_id: nil)
  end

  def create
    if params[:recipe]
      @recipe = Recipe.find(params[:recipe])
      @recipe.ingredient_recipes.each do |ingredient_recipe|
        detail_basket = DetailBasket.new(ingredient_recipe_id: ingredient_recipe.id,
                                         ingredient_quantity: (ingredient_recipe.ingredient_quantity * @recipe.person_number))
        detail_basket.basket_id = current_user.baskets.first.id
        detail_basket.save
      end

      flash[:notice] = "#{@recipe.name} successfully added"
      redirect_to recipes_path

    else
      @ingredient = Ingredient.find(params[:detail_basket][:ingredient].to_i)
      detail_basket = DetailBasket.new(ingredient_id: @ingredient.id, ingredient_quantity: params[:detail_basket][:ingredient_quantity].to_i)
      detail_basket.basket_id = current_user.baskets.first.id
      detail_basket.save
      flash[:notice] = "#{@ingredient.name} successfully added"
      redirect_to ingredients_path(category: @ingredient.category, anchor: "ingredient-#{@ingredient.id}")
    end
  end

  def destroy
    if params[:id]
      @detail_basket.destroy
      redirect_to detail_baskets_path
    end
  end

  def edit
  end

  def update
    @detail_basket.update(detail_basket_params)
    redirect_to basket_path(current_basket)
  end

  private

  def set_detail_basket
    @detail_basket = DetailBasket.find(params[:id])
  end
end

app/views/detail_baskets/index.html.erb
<div class="container">
  <h1 class= "basket-title title-recipe-index">-My Basket-</h1>
  <div class="basket-content">

    <% recipe = [] %>
    <% if @detail_baskets.empty? %>

      <%# <div class="empty_basket"> %>
      <div class="basket_empty">
        <h4>Your basket is empty for now...</h4>
        <img src="https://cdn2.iconfinder.com/data/icons/outline-web-application-1/20/cart-512.png" alt="" id="img-empty" >
      </div>
      <%# </div> %>

    <% else %>
      <% unless @recipes.empty? %>
        <div class="card-title" id="title-recipe">
          <div class="opacity-recipe">
            <h1>RECIPES</h1>
          </div>
        </div>
      <% end %>

      <% @recipes.each do |detail| %>
        <% unless recipe.include?(detail.ingredient_recipe.recipe) %>
          <div class="card-basket card-basket-recipe d-flex justify-content-between">
            <div class="recipe-name">
              <h5><%= detail.ingredient_recipe.recipe.name %></h5>
            </div>

            <div class="recipe-img">
              <%= cl_image_tag detail.ingredient_recipe.recipe.photo.key, crop: :fill,  class: "recipe-image"%>
            </div>
          </div>
        <% end %>

        <% recipe << detail.ingredient_recipe.recipe %>

          <ul>
            <div class="card-basket card-basket-ingredient-recipe">
              <%= detail.ingredient_quantity.round(1) %> <%= detail.ingredient_recipe.ingredient.unit %> |
              <%= detail.ingredient_recipe.ingredient.name %>

              <%= link_to detail_basket_path(id:detail.id),method: :delete, class:'basket-bin' do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
            </div>
          </ul>

      <% end %>



      <% unless @products.empty? %>
        <div class="card-title" id="title-product">
          <div class="opacity-recipe">
            <h1>PRODUCTS</h1>
          </div>
        </div>

        <% end %>
        <% @products.each do |product| %>
            <div class="card-basket card-basket-ingredient-recipe mb-2">
              <%= product.ingredient_quantity.round(1) %> <%= product.ingredient.unit %> |
              <%= product.ingredient.name %>

            <%= link_to detail_basket_path(id:product.id),method: :delete, class:'basket-bin' do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
      <% end %>

    </div>

    <div class="link-to-basket">
      <%= link_to basket_path(@basket) do %>
        <div class="btn-show">
          <p class="color-white">Continue to your list</p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>