config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user_sessions" }

  root to: 'pages#newhome'
  get '/home',  to: 'pages#home',  as: 'home'
  get '/order', to: 'pages#order', as: 'order'
  get '/category', to: 'pages#category', as: 'category'
  get '/my_list', to: 'pages#my_list', as: 'my_list'
  authenticate :user do
    resources :users, only: [:show, :update, :edit]

    resources :recipes, only: [:new, :create, :edit]
    resources :baskets, only: [:create, :show]

    resources :detail_baskets, only: [:create, :index, :destroy]
  end

  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]
end

app/views/pages/category.html.erb
<div class="container" id="search-category">
    <%= form_tag ingredients_path, method: :get do %>
    <div class="d-flex search">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control", id:"form-control-search",
        placeholder: "Find an ingredient"%>
        <%= button_tag(type:"submit", class: "btn btn-flat", id:"btn-ingredient") do %>
            <i class="fas fa-search text-decoration-none text-white h4"></i>
        <% end %>
    </div>
    <% end %>
</div>
  
<div class="container-category">
    <div class="d-flex justify-content-between">
        <%= link_to ingredients_path(category: "vegetables") do%>
            <div class="card-category" id="vegetable">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Vegetables</strong></h3>
                </div>
            </div>
        <% end %>
        <%= link_to ingredients_path(category: "fruits") do%>
            <div class="card-category" id="fruits">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Fruits</strong></h3>
                </div>
            </div>
        <% end %>
    </div>
    <div class="d-flex justify-content-between">
        <%= link_to ingredients_path(category: "dry") do%>
            <div class="card-category" id="dry">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Dry</strong></h3>
                </div>
            </div>
        <% end %>
        <%= link_to ingredients_path(category: "condiment") do%>
            <div class="card-category" id="condiment">
                <div class="opacity-category">
                    <h3 class="padding10 categorie"><strong>Condiment</strong></h3>
                </div>
            </div>
        <% end %>
    </div>
    <div class="d-flex justify-content-between">
        <%= link_to ingredients_path(category: "meat") do%>
            <div class="card-category" id="meat">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Meat</strong></h3>
                </div>
            </div>
        <% end %>
        <%= link_to ingredients_path(category: "seafood") do%>
            <div class="card-category" id="seafood">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Seafood</strong></h3>
                </div>
            </div>
        <% end %>
    </div>
    <div class="d-flex justify-content-between">
        <%= link_to ingredients_path(category: "dairy milk"), class:'text-decoration-none' do %>
            <div class="card-category" id="diary">
                <div class="opacity-category">
                    <h3 class="padding8 categorie"><strong>Dairy products</strong></h3>
                </div>
            </div>
        <% end %>
        <%= link_to ingredients_path(category: "drinks"), class:'text-decoration-none' do %>
            <div class="card-category" id="drinks">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Drinks</strong></h3>
                </div>
            </div>
        <% end %>
    </div>
    <div class="d-flex justify-content-between">
        <%= link_to ingredients_path(category: "cater"), class:'text-decoration-none' do %>
            <div class="card-category" id="cater">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Cater</strong></h3>
                </div>
            </div>
        <% end %>
        <%= link_to ingredients_path(category: "pastry"), class:'text-decoration-none' do %>
            <div class="card-category" id="pastry">
                <div class="opacity-category">
                    <h3 class="padding11 categorie"><strong>Pastry</strong></h3>
                </div>
            </div>
        <% end %>
    </div>
</div>
<br><br><br>

app/views/pages/home.html.erb
<div class='container home-container'>

  <div class='row'>
    <div class='col-12'>
      <%= link_to my_list_path, class:'text-decoration-none' do %>
        <div class='card-banner' id='card-banner-list'>
          <span class='card-banner-text color-black'><strong class="title-card-home text-shadow-white">My List</strong></span>
        </div>
      <% end %>
    </div>
  </div>

  <div class='row'>
    <div class='col-12'>
      <%= link_to recipes_path, class:'text-decoration-none' do %>
        <div class='card-banner' id='card-banner-recipes'>
          <span class='card-banner-text color-white'><strong class="title-card-home text-shadow-black">Recipes</strong></span>
        </div>
      <% end %>
    </div>
  </div>

  <div class='row'>
    <div class='col-12'>
      <%= link_to category_path, class:'text-decoration-none' do %>
        <div class='card-banner' id='card-banner-ingredients'>
          <span class='card-banner-text color-black'><strong class="title-card-home text-shadow-white">Shop</strong></span>
        </div>
      <% end %>
    </div>
  </div>

  <div class='row'>
    <div class='col-12'>
      <div class='card-banner' id="card-best-rec">
        <span class='card-banner-text top-rated'>Top rated recipes</span>
      </div>
    </div>
  </div>

  <div class='container-scroll'>
    <% @recipes.sample(10).each do |recipe|  %>
      <div class='row'>
        <div class='col'>
          <%= link_to recipe_path(recipe), class:"text-decoration-none" do %>
            <div class="card-scroll">
              <%= cl_image_tag recipe.photo.key, crop: :fill,  class: "recipe-image-home"%>
              <div>
                <h5 class="card-title-best-recipe color-white" id="body-scroll"><%= recipe.name %></h5>
              </div>

              <div class="d-flex justify-content-center">
                <div class="small-line-under">
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
      
  <!--Effacer quand la home est terminée-->
  <br><br><br><br>
</div>

app/views/pages/my_list.html.erb
<div class="container">
  <h1 class="title-recipe-index">-Your List-</h1>
  <div>
    <h4 class="my-list-desc mylist-opacity">Fill your profile page & we'll <span class="orange">suggest</span> a list according to <span class="orange">your preferences</span> and <span class="orange">habits</span> </h4>
  </div>
  <div class="my-list">

    <div class="btn-add-an-ingredient">
      <%= link_to category_path do %>
        <h4 class="btn-add"><i class="fas fa-plus"></i></h4>
      <% end %>
    </div>
    

  <div class="alert ugo" role="alert">
    <%= alert %>
    <div class="my-list-pop-up">
      <h4>LET'S TRY <span class="your-list">YOUR LIST</span> !</h4> <br>
      <h3><span class="simple">SIMPLE</span>, <br><span class="fast">FAST</span> <br>& <span class="easy">EASY</span> ! </h3> <br><br><br>
      <h4 class="my-list-desc">Get <span>suggestions</span> according to <span>your preferences</span> & <span>habits</span> </h4>
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
<!--       <h2 class="try-it"> try it !</h2> -->
      <span aria-hidden="true">&times;</span>
    </button>
  </div>


  
    <div class="head-list">
      <div class="item">
        <strong><p>Item</p></strong>
      </div>
      <div class="qty-price-amt">
        <strong><p>Qty</p></strong>
        <strong><p>Price</p></strong>
        <strong><p>Amt</p></strong>
      </div>
    </div>


    <% category = [] %>
    <% ingredient = [] %>
    <% amt = 0 %>
    <% @final_basket.each do |detail| %>
    
      <% unless category.include?(detail[:category]) %>

        <div class="ingredient-category">
          <h5><strong>-----  <%= detail[:category].upcase %>  -----</strong></h5>
        </div>

      <% end %>
      <% category << detail[:category] %>

        <div class="body-list">
          <div class="item">
            <strong><%= detail[:name].capitalize %></strong>
          </div>



          <div class="qty-price-amt">
            <p><%= detail[:quantity].round(1) %> <%= detail[:unit] %></p>
            <p><%= detail[:price] %> €/ <%= detail[:unit] %> </p>
            <p><%= (detail[:quantity] * detail[:unit_price]).round(4) %>
            <% amt += (detail[:quantity] * detail[:unit_price]).round(4) %> $
            </p>
          </div>
        </div>


    <% end %>

    <div class="footer-list">
      <div class="item">
        <strong><p>SubTotal</p></strong>
      </div>
      <div class="qty-price-amt">
        <strong><h5><%= amt.round(2) %> € </h5></strong>
      </div>
    </div>

  </div>
  

  <%############ popup %>
  <%= link_to order_path  do %>
    <h4 class="btn-show color-white">Order</h4>
  <% end %>
</div>

app/views/pages/newhome.html.erb
<div class="background-new-home">
  <div class="opacity">
    <div class="text-newhome">
        <h1 class="h1-newhome"><strong>Welcome to <span>My List</span></strong></h1>
        <h3 class="h3-newhome"><span>Simplify</span> your grocery shopping.</h3>
    </div>
    <% if current_user == nil %>

      <div class="link">
          <%= link_to "Log in", new_user_session_path, class:"btn-home-signup-width"%>
      </div>
<!--       <div class="link">
          <%#= link_to "Sign up now",  new_user_registration_path, class:"btn-home-signup"%>
      </div>
      <div class="link-home">
          <%#= link_to "Continue without sign up", home_path, class:"btn-home" %>
      </div> -->

    <% else %>
      <div class="link">
          <%= link_to "Continue", home_path, class:"btn-home-signup", id:"continue"%>
      </div>

    <% end %>
  </div>
</div>

app/views/pages/order.html.erb
<div class="alert alert-info" id="satine" role="alert">
    <%= notice %>
    <div class="d-flex justify-content-center satine-loader">
        <div class="spinner-border text-success satine-loader-center" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
</div>


<div class="fruit">
    <div class="opacity-order">
        <div class="card-order">
            <h2 class="title-order"><strong>Your order is confirmed !</strong></h2>
            <h4 class="text-order center"><strong>Thank to shopping with us</strong></h4>
            <div class="padding-order">
                <h5 class="text-order">Order number: <%= current_user.baskets.first.id %></h5>
                <h5 class="text-order">Order date: <%= Date.today %></h5>
                <h5 class="text-order">Delivery date: <%= Date.today%> in 1 minute</h5>
            </div>
        </div>
    </div>
</div>

app/views/pages/text.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img height='200px' class="d-block w-100" src="https://image.flaticon.com/icons/png/512/1046/1046857.png" alt="First slide">
    </div>
    <div class="carousel-item">
      <img height='200px' class="d-block w-100" src="https://image.flaticon.com/icons/png/512/1046/1046857.png" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img height='200px' class="d-block w-100" src="https://image.flaticon.com/icons/png/512/1046/1046857.png" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>